articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name = "index"),
    path('<int:article_id>/', views.detail, name = "detail"),
    path('<int:article_id>/leave_comment/', views.leave_comment, name="leave_comment"),
    path('new/', views.new, name="new"),
    path('<int:article_id>/edit/', views.edit, name="edit"),
    path('<int:article_id>/delete/', views.delete, name="delete"),
    path('<int:article_id>/rate/', views.rate, name="article-rate"),
    path('<int:article_id>/like/', views.like, name="article-like"),
    path('search/', views.search, name="search"),
    path('bytags/<int:tag_id>', views.bytags, name="bytags"),
]

qwe/urls.py
from django.contrib import admin
from django.urls import path, include
from filebrowser.sites import site
from articles.views import home, userprofile, theme
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', home, name='home'),
    path('tinymce/', include('tinymce.urls')),
    path('admin/filebrowser/', site.urls),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile', userprofile, name='userprofile'),
    path('theme', theme, name='theme'),
]
if settings.DEBUG: urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User
from tinymce.models import HTMLField
from taggit.managers import TaggableManager
from django.db.models.aggregates import Avg


GROUPS = [
    ('Книги','Книги'),
    ('Игры','Игры'),
    ('Фильмы','Фильмы'),
]
MARKS = [
    (1,'1 - Отвратительно'),
    (2,'2 - Ужасно'),
    (3,'3 - Плохо'),
    (4,'4 - Удовлетворительно'),
    (5,'5 - Нормально'),
    (6,'6 - Хорошо'),
    (7,'7 - Очень хорошо'),
    (8,'8 - Замечательно'),
    (9,'9 - Прекрасно'),
    (10,'10 - Шедеврально'),
]

class Article(models.Model):
    author_name = models.CharField('Имя автора', max_length = 50)
    article_title = models.CharField('Название статьи', max_length = 200)
    article_text = HTMLField('Текст статьи')
    pub_date = models.DateTimeField('Дата публикации')
    likes = models.PositiveIntegerField('Количество лайков', default=0)
    tags = TaggableManager()
    group = models.CharField('Категория',choices=GROUPS, max_length=6, default='')
    author_mark = models.PositiveSmallIntegerField('Оценка автора', choices=MARKS, default=0, blank=False)

    def __str__(self):
        return self.article_title
    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=7))
    def avg_rating(self, mode=1):
        ratings = Rating.objects.filter(article=self)
        ratings_avg = ratings.aggregate(Avg('rate')).get('rate__avg')
        ratings_count = ratings.count()
        if mode==1:
            return ratings_avg
        elif mode==2:
            return ratings_avg, ratings_count
    def best(self):
        return self.avg_rating()>=4.5
    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"

RATE_CHOISES = [
    (1, '1 - Ужасно'),
    (2, '2 - Плохо'),
    (3, '3 - Нормально'),
    (4, '4 - Хорошо'),
    (5, '5 - Великолепно'),
]
class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    rate = models.PositiveSmallIntegerField(choices=RATE_CHOISES)
    class Meta:
        verbose_name="Рейтинг"
        verbose_name_plural="Рейтинги"
    def __str__(self):
        return f'{self.article} - {self.rate}'

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('Имя автора', max_length = 50)
    comment_text = models.CharField('Текст комментария', max_length = 300)
    def __str__(self):
        return self.comment_text
    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

class Like(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    type_like = models.PositiveSmallIntegerField(choices=[(0, 'Не лайкнуто'),
                                                            (1, 'Лайкнуто')],default=0)
    class Meta:
        verbose_name="Лайк"
        verbose_name_plural="Лайки"

class Theme(models.Model):
    color = models.CharField(max_length=10)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.user

articles/forms.py
from django import forms
from .models import Article, Rating, RATE_CHOISES

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('article_title', 'group', 'article_text', 'author_mark', 'tags')

class RatingForm(forms.ModelForm):
    rate = forms.ChoiceField(choices=RATE_CHOISES, widget=forms.Select(), required=True)
    class Meta:
        model=Rating
        fields=('rate',)

articles/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Article, Rating, Like, Comment, Theme
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from .forms import ArticleForm, RatingForm
from django.utils import timezone
from django.contrib.postgres.search import SearchVector
from taggit.models import Tag

def home(request):
    latest_articles_list = Article.objects.order_by('-pub_date')[:5]
    best = Article.objects.order_by('-likes')[:3]
    tags = Tag.objects.all()
    if not request.user.is_authenticated:
        color = 'light'
        return render(request, 'base.html', {'latest_articles_list': latest_articles_list,
                                             'best': best,
                                             'tags': tags,
                                             'color': color})
    elif Theme.objects.filter(user=request.user).exists():
        color=Theme.objects.get(user=request.user).color
    else:
        color='light'
    return render(request, 'base.html', {'latest_articles_list': latest_articles_list,
                                         'best':best,
                                         'tags':tags,
                                         'color':color})

def userprofile(request):
    if request.user.is_superuser:
        article_list = Article.objects.all()
    else:
        article_list = Article.objects.filter(author_name=request.user.username)
    likes_count=0
    for a in article_list:
        likes_count+=a.likes

    if not request.user.is_authenticated:
        color = 'light'
    elif Theme.objects.filter(user=request.user).exists():
        color=Theme.objects.get(user=request.user).color
    else:
        color='light'
    return render(request, 'account/userprofile.html', {'article_list': article_list,
                                                        'likes_count':likes_count,
                                                        'color':color})

def index(request):
    articles_list = Article.objects.order_by('-pub_date')
    if not request.user.is_authenticated:
        color = 'light'
    elif Theme.objects.filter(user=request.user).exists():
        color=Theme.objects.get(user=request.user).color
    else:
        color='light'
    return render(request, 'articles/list.html', {'articles_list': articles_list,
                                                  'color':color})

def detail(request, article_id, form=0):
    try:
        a = Article.objects.get(id = article_id)
    except:
        raise Http404("Статья не найдена!")
    latest_comment_list = a.comment_set.order_by('-id')
    ratings_avg, ratings_count = a.avg_rating(2)
    group = a.group
    form = RatingForm()

    if not request.user.is_authenticated:
        color = 'light'
    elif Theme.objects.filter(user=request.user).exists():
        color=Theme.objects.get(user=request.user).color
    else:
        color='light'

    return render(request, 'articles/detail.html', {'article': a,
                                                    'latest_comment_list': latest_comment_list,
                                                    'ratings_avg':ratings_avg,
                                                    'ratings_count':ratings_count,
                                                    'form':form,
                                                    'group':group,
                                                    'color':color})

def like(request, article_id):
    user_liking = request.user
    article = Article.objects.get(id=article_id)
    current_likes = article.likes
    liked = Like.objects.filter(user=user_liking, article=article, type_like=1).count()
    if not liked:
        like = Like.objects.create(user=user_liking, article=article, type_like=1)
        current_likes+=1
    else:
        Like.objects.filter(user=user_liking, article=article, type_like=1 ).delete()
        current_likes-=1

    article.likes = current_likes
    article.save()
    return HttpResponseRedirect( reverse('articles:detail', args=(article.id,)) )

def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Статья не найдена!")
    a.comment_set.create(author_name=request.user.username, comment_text=request.POST['text'])
    return HttpResponseRedirect( reverse('articles:detail', args=(a.id,)) )

def rate(request, article_id):
    try:
        article = Article.objects.get(id=article_id)
    except:
        raise Http404("Статья не найдена!")
    user = request.user
    r = Rating.objects.filter(user=user, article=article)
    if request.method == 'POST':
        form = RatingForm(request.POST)
        if form.is_valid():
            if r:
                r.delete()
            rate = form.save(commit=False)
            rate.user = user
            rate.article = article
            rate.save()
    else: return Http404("Что-то пошло не так")
    return HttpResponseRedirect( reverse('articles:detail', args=(article.id,)) )

def new(request):
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.author_name = request.user.username
            article.pub_date = timezone.now()
            article.save()
            form.save_m2m()
            return HttpResponseRedirect( reverse('articles:detail', args=(article.id,)) )
    else:
        form = ArticleForm()

    if Theme.objects.filter(user=request.user).exists():
        color=Theme.objects.get(user=request.user).color
    else:
        color='light'
    return render(request, 'articles/edit.html', {'form': form,
                                                  'color':color})

def edit(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    if request.method == "POST":
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            article = form.save(commit=False)
            article.pub_date = timezone.now()
            article.save()
            form.save_m2m()
            return HttpResponseRedirect( reverse('articles:detail', args=(article.id,)) )
    else:
        form = ArticleForm(instance=article)

    if Theme.objects.filter(user=request.user).exists():
        color=Theme.objects.get(user=request.user).color
    else:
        color='light'
    return render(request, 'articles/edit.html', {'form': form,
                                                  'color':color})

def delete(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    article.delete()
    return userprofile(request)

def search(request):
    if not request.user.is_authenticated:
        color = 'light'
    elif Theme.objects.filter(user=request.user).exists():
        color = Theme.objects.get(user=request.user).color
    else:
        color = 'light'
    if request.method == "POST":
        searched = request.POST.get('searched')

        articles = Article.objects.annotate(search=SearchVector('article_title')).filter(search=str(searched))
        text = Article.objects.annotate(search=SearchVector('article_text')).filter(search=str(searched))
        comments = Comment.objects.annotate(search=SearchVector('comment_text')).filter(search=str(searched))
        tags = Article.objects.filter(tags__name__in=[searched])

        return render(request, 'articles/search.html', {'searched':searched, 'in_articles':articles,
                                                        'in_text':text, 'in_tags':tags,
                                                        'in_comments':comments, 'color':color})
    else:
        return render(request, 'articles/search.html', {'color':color})

def bytags(request, tag_id):
    tag = get_object_or_404(Tag,id=tag_id)
    articles = Article.objects.filter(tags__name__in=[tag.name])
    if not request.user.is_authenticated:
        color = 'light'
    elif Theme.objects.filter(user=request.user).exists():
        color=Theme.objects.get(user=request.user).color
    else:
        color='light'
    return render(request, 'articles/bytags.html',{'articles': articles,
                                                   'tagname':tag.name,
                                                   'color':color})

def theme(request):
    color = request.GET.get('color')
    if color == 'dark':
        if Theme.objects.filter(user=request.user).exists():
            user_theme = Theme.objects.get(user=request.user)
            user_theme.user = request.user
            user_theme.color = 'secondary'
            user_theme.save()
        else:
            user2=Theme(user=request.user, color='secondary')
            user2.save()
    elif color == 'light':
        if Theme.objects.filter(user=request.user).exists():
            user_theme1 = Theme.objects.get(user=request.user)
            user_theme1.user = request.user
            user_theme1.color = 'light'
            user_theme1.save()
        else:
            user4=Theme(user=request.user, color='light')
            user4.save()
    return redirect('/')

templates/articles/bytags.html
{% extends 'base.html' %}

{% block title %}Поиск по облаку тегов{% endblock %}
{% block theme %}class="bg-{{ color }} text-dark"{% endblock %}
{% block content %}

    <div style="text-align: center;">
        {% if articles %}
            <div>
                <h1 class="mt-4">Статьи с тегом "{{ tagname }}"</h1>
                <br>
            </div>

            <div class="intags">
                {% for a in articles %}
                    <a href={% url 'articles:detail' a.id %}>{{ a.article_title }}</a>
                    <p>теги: {{ a.tags.all|join:", "  }}</p>
                    <em>by {{ a.author_name }}</em><br>
                {% endfor %}
            </div>
        {% else %}
            Что-то пошло не так
        {% endif %}
        <hr>
        <a class="btn btn-outline-dark" href="{% url 'articles:index' %}"><span
                class="bi bi-card-list"></span> Перейти к списку статей</a><br>
    </div>
{% endblock %}

templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}{{ article.article_title }}{% endblock %}

{% block theme %}class="bg-{{ color }} text-dark"{% endblock %}

{% block content %}
    {% if color == 'light' %}
        <a class="btn btn-outline-dark mb-4" href="{% url 'articles:index' %}"><span
                class="bi bi-card-list"></span> Перейти к списку статей</a><br>
    {% else %}
        <a class="btn btn-outline-light mb-4" href="{% url 'articles:index' %}"><span
                class="bi bi-card-list"></span> Перейти к списку статей</a><br>
    {% endif %}

    {% if user.is_authenticated %}
        {% if user.is_superuser or user.username == article.author_name %}
            <a class="btn btn-info" href="{% url 'articles:edit' article.id %}">Редактировать</a>
        {% endif %}
    {% endif %}

    <h2>{{ article.article_title }}</h2>
    <em>by {{ article.author_name }}</em><br>
    <em>Категория: {{ article.group }}</em>
    {% if ratings_avg %}
        <h3><strong>Рейтинг: {{ ratings_avg }} / 5</strong></h3>
        <h5><em>Проголосовало пользователей: {{ ratings_count }}</em></h5>
    {% else %}
        <h4><strong>Статья не оценена ни одним пользователем. Будьте первым, кто выставит рейтинг!</strong></h4>
    {% endif %}

    {% if article.tags.all %}
        <em>Теги: <strong>{{ article.tags.all|join:", "  }}</strong></em>
    {% else %}
        <em>У данной статьи не указаны теги</em>
    {% endif %}
    <hr>
    <div class="">
        <p>{{ article.article_text|safe }}</p>
    </div>
    <p>Оценка автора: {{ article.author_mark }}</p>

    <em>{{ article.pub_date }}</em>

    {% if article.was_published_recently %}
        <em>| New!</em>
    {% endif %}

    <hr>
    {% if user.is_authenticated %}

        <div class="card-action">
        <a class="btn btn-primary" href="{% url 'articles:article-like' article.id %}" class="top-menu">Мне нравится {{ article.likes }}</a><br>
        </div>

        <br>
        <div>
            <h3>Оцените статью</h3>
            <form method="post" action="{% url 'articles:article-rate' article.id %}" role="form" class="col s12">
                {% csrf_token %}

                <div class="input-field col s12">
                    {{ form.rate }}
                </div>
                <button type="submit" name="action" class="btn btn-outline-secondary">Оценить</button>
            </form>
        </div>

        <hr>
        <h3>Оставьте комментарий</h3>
        <form action="{% url 'articles:leave_comment' article.id %}" method="post">
        {% csrf_token %}
        <textarea name="text" required="" placeholder="Ваш комментарий" cols="30" rows="10"></textarea><br>
        <button type="submit" class="btn btn-primary">Оставить комментарий</button>
        </form>

        <hr>
        <h3><strong>Комментарии</strong></h3>
    {% if latest_comment_list %}

        {% for c in latest_comment_list %}
        <p>
            <strong>{{ c.author_name }}</strong>
            <p>{{ c.comment_text }}</p>
        </p>
        {% endfor %}
    {% else %}
        К данной статье нет комментариев.
    {% endif %}
    {% else %}
        <em>Авторизуйтесь, чтобы ставить лайки, смотреть и оставлять комментарии, а также выставлять рейтинг</em>
    {% endif %}
{% endblock %}

templates/articles/edit.html
{% extends 'base.html' %}

{% block tinymce %}
    <script src="https://cdn.tiny.cloud/1/ynenkeysawvl07v3ruqmlbbbg68tlerd4q6swxc0ddig23ew/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
{% endblock %}

{% block title %}Редактирование статьи{% endblock %}
{% block theme %}class="bg-{{ color }} text-dark"{% endblock %}
{% block content %}
    <a class="btn btn-danger top-menu" href="{% url 'articles:index' %}">Отмена</a><br>
    <h1>Редактирование статьи</h1>
    <script>
    tinymce.init({
        language:'ru',
      selector: 'textarea',
        images_upload_url: 'https://drive.google.com/drive/folders/1hmeswUcLclMjPMvOsnkiOFbBtQgblWmw?usp=sharing',
      plugins: 'casechange formatpainter linkchecker autolink lists checklist media permanentpen table paste link autoresize',
        width: '100%',
        menubar: "format insert",
      toolbar: 'casechange checklist formatpainter paste permanentpen table link media',
      toolbar_mode: 'floating',
        paste_data_images: true,
    });
  </script>
    <div class="fieldBox">
        <form method="POST" class="post-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Сохранить</button>
        </form>
    </div>
{% endblock %}

templates/articles/list.html
{% extends 'base.html' %}

{% block title %}Последние обзоры{% endblock %}
{% block theme %}class="bg-{{ color }} text-dark"{% endblock %}
{% block content %}
    <div style="text-align: center;">
        <h3>Список статей</h3>
        {% if user.is_authenticated %}
            <a class="btn btn-success" href="{% url 'articles:new' %}">Новая статья</a>
        {% endif %}
    </div>

    {% if articles_list %}
        <div style="text-align: center;">
            {% for a in articles_list %}
                <div class="col d-flex justify-content-center">
                    <div class="card w-75 bg-{{ color }} text-dark">
                        <div class="card-body">
                            <h5 class="card-title">{{a.article_title}}</h5>
                            <em class="card-text">by {{ a.author_name }}</em>
                            <p><em>Опубликовано: {{ a.pub_date }}</em><br>теги: {{ a.tags.all|join:", "  }}</p>
                            <a class="btn btn-primary" href={% url 'articles:detail' a.id %}>Перейти</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        Статьи не найдены. Будьте первым!
    {% endif %}

{% endblock %}

templates/articles/search.html
{% extends 'base.html' %}

{% block theme %}class="bg-{{ color }} text-dark"{% endblock %}
{% block content %}

    <div style="text-align: center;">
        <div>
            {% if searched %}
                {% if searched|length < 70 %}
                    <h1>Вы искали "{{ searched }}"</h1>
                    <br>
                {% else %}
                    <h1>Вы искали "{{ searched|slice:70 }}..."</h1>
                    <br>
                {% endif %}
        </div>
        <div class="inarticles">
                {% if in_articles %}
                    <h1>Совпадения по заголовкам</h1>
                    {% for a in in_articles %}
                    <div class="col d-flex justify-content-center">
                    <div class="card w-50 bg-{{ color }} text-dark">
                        <div class="card-body">
                            <h5 class="card-title">{{a.article_title}}</h5>
                            <em class="card-text">by {{ a.author_name }}</em>
                            <p><a class="btn btn-primary" href={% url 'articles:detail' a.id %}>Перейти</a></p>
                        </div>
                    </div>
                </div>
                    {% endfor %}
                {% endif %}
        </div>
        <div class="intext">
                {% if in_text %}
                    <h1>Совпадения по тексту</h1>
                    {% for a in in_text %}
                    <div class="col d-flex justify-content-center">
                    <div class="card w-50 bg-{{ color }} text-dark">
                        <div class="card-body">
                            <h5 class="card-title">{{a.article_title}}</h5>
                            <em class="card-text">by {{ a.author_name }}</em>
                            <p><a class="btn btn-primary" href={% url 'articles:detail' a.id %}>Перейти</a></p>
                        </div>
                    </div>
                </div>
                    {% endfor %}
                {% endif %}
        </div>
        <div class="intags">
                {% if in_tags %}
                    <h1>Совпадения по тегам</h1>
                    {% for t in in_tags %}
                    <div class="col d-flex justify-content-center">
                    <div class="card w-50 bg-{{ color }} text-dark">
                        <div class="card-body">
                            <h5 class="card-title">{{t.article_title}}</h5>
                            <em class="card-text">by {{ t.author_name }}</em>
                            <p>теги: {{ t.tags.all|join:", "  }}</p>
                            <p><a class="btn btn-primary" href={% url 'articles:detail' t.id %}>Перейти</a></p>
                        </div>
                    </div>
                </div>
                    {% endfor %}
                {% endif %}
        </div>
        <div class="incomments">
                {% if in_comments %}
                    <h1>Совпадения по комментариям</h1>
                    {% for c in in_comments %}
                        <div class="col d-flex justify-content-center">
                            <div class="card w-50 bg-{{ color }} text-dark">
                                <div class="card-body">
                                    <h5 class="card-title">{{c.article.article_title}}</h5>
                                    <p><em class="card-text">by {{ c.article.author_name }}</em></p>
                                    {% if user.is_authenticated %}
                                        <em>Комментарий пользователя {{c.author_name}}:</em>
                                        {% if c.comment_text|length > 50 %}
                                            <a>{{ c.comment_text|slice:50}}...</a>
                                        {% else %}
                                            <a>{{ c.comment_text }}</a>
                                        {% endif %}
                                    {% else %}
                                        <em>Чтение комментариев доступно только аутентифицированным пользователям</em>
                                    {% endif %}
                                    <p><a class="btn btn-primary" href={% url 'articles:detail' c.article.id %}>Перейти</a></p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
        </div>
            {%if not in_articles and not in_text and not in_comments and  not in_tags %}
                <h1>Ничего не найдено</h1>
            {% endif %}
        {% else %}
            <h1>Поисковый запрос пуст. Попробуйте ввести что-то, вдруг получится лучше =)</h1>
        {% endif %}
        <hr>
    {% if color == 'light' %}
        <a class="btn btn-outline-dark" href="{% url 'articles:index' %}"><span
                class="bi bi-card-list"></span> Перейти к списку статей</a><br>
    {% else %}
        <a class="btn btn-outline-light" href="{% url 'articles:index' %}"><span
                class="bi bi-card-list"></span> Перейти к списку статей</a><br>
    {% endif %}
    </div>
{% endblock %}