articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name = "index"),
    path('<int:article_id>/', views.detail, name = "detail"),
    path('<int:article_id>/leave_comment/', views.leave_comment, name="leave_comment"),
    path('new/', views.new, name="new"),
    path('<int:article_id>/edit/', views.edit, name="edit"),
    path('<int:article_id>/delete/', views.delete, name="delete"),
    path('<int:article_id>/rate/', views.rate, name="article-rate"),
    path('<int:article_id>/like/', views.like, name="article-like"),
    path('search/', views.search, name="search"),
    path('bytags/<int:tag_id>', views.bytags, name="bytags"),
]

qwe/urls.py
from django.contrib import admin
from django.urls import path, include
from filebrowser.sites import site
from articles.views import home, userprofile, theme
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', home, name='home'),
    path('tinymce/', include('tinymce.urls')),
    path('admin/filebrowser/', site.urls),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile', userprofile, name='userprofile'),
    path('theme', theme, name='theme'),
]
if settings.DEBUG: urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
{% block tinymce %}{% endblock %}

    <meta charset="UTF-8">
    <title>{% block title %}NedoKinopoisk{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <meta name="google" content="notranslate" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
</head>
<body {% block theme %}class="bg-{{ color }} text-dark"{% endblock %}>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<header class="navbar navbar-expand-lg navbar-light bg-dark margin-bottom 25px d-flex">
    <div class="container-fluid">.bg-dark
        <a class="navbar-brand" href="{% url 'home' %}" role="button"><button type="button" class="btn btn-dark">NedoKinopoisk</button></a>
        {% if user.is_authenticated %}
            <a style="color: #9a9a9a">Добро пожаловать, {{ user.username }}</a>
            <a class="navbar-link" href="{% url 'userprofile' %}" role="button"><button type="button" class="btn btn-dark">Профиль</button></a>

            <a class="navbar-link" href="{% url 'account_logout' %}" role="button"><button type="button" class="btn btn-dark">Выйти</button></a>
        {% else %}
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="navbar-link" href="{% url 'account_login' %}" role="button"><button type="button" class="btn btn-dark">Войти</button></a>
                </li>
                <li class="nav-item">
                    <a class="navbar-link" href="{% url 'account_signup' %}" role="button"><button type="button" class="btn btn-dark">Зарегистрироваться</button></a>
                </li>
            </ul>
            </div>
        {% endif %}
        <form class="d-flex" method="post" action="{% url 'articles:search' %}">
            {% csrf_token %}
            <input class="form-control me-2" type="search" placeholder="Поиск"
                   aria-label="Search" name="searched">
            <button class="btn btn-outline-success" type="submit">Поиск</button>
        </form>
    </div>
</header>

{% block content %}
    <br>
        {% if color == 'light' %}
            <a class="btn btn-outline-dark" href="{% url 'articles:index' %}">Все статьи</a>
        {% else %}
            <a class="btn btn-outline-light" href="{% url 'articles:index' %}">Все статьи</a>
        {% endif %}
    <br>

    {% if latest_articles_list %}
        <div style="text-align: center;">
            <h3>Свежие статьи</h3>
        </div>
            {% for a in latest_articles_list %}
                <div class="col d-flex justify-content-center">
                <div class="card w-75 bg-{{ color }} text-dark">
                    <div class="card-body">
                        <h5 class="card-title">{{a.article_title}}</h5>
                        <em class="card-text">by {{ a.author_name }}</em>
                        <p><em>Опубликовано: {{ a.pub_date }}</em><br>теги: {{ a.tags.all|join:", "  }}</p>
                        <p>Категория: {{ a.group }}; Рейтинг: {{ a.avg_rating }}</p>

                        <a class="btn btn-primary" href={% url 'articles:detail' a.id %}>Перейти</a>
                    </div>
                </div>
                </div>
            {% endfor %}
    {% else %}
            {% if user.is_authenticated %}
                <h3>Давненько на этом сайте не было статей. Исправьте это, напишите свою!</h3>
                <a class="btn btn-outline-secondary" href="{% url 'articles:new' %}">Новая статья</a>
            {% else %}
                <h3>Давненько на этом сайте не было статей. Исправьте это, авторизуйтесь и напишите свою!</h3>
            {% endif %}
    {% endif %}

    <div style="text-align: center;">
    <hr>
        <h3>Лучшие статьи</h3>
        {% if best %}
            {% for b in best %}
                <div class="col d-flex justify-content-center">
                    <div class="card w-50 bg-{{ color }} text-dark">
                        <div class="card-body">
                            <h5 class="card-title">{{b.article_title}}</h5>
                            <em class="card-text">by {{ b.author_name }}</em>
                            <p><em>Опубликовано: {{ b.pub_date }}</em><br>теги: {{ b.tags.all|join:", "  }}</p>
                            <p>Категория: {{ b.group }}</p>
                            <p>Лайков: {{ b.likes }}</p>
                            <p>Рейтинг: {{ b.avg_rating }}</p>
                            <a class="btn btn-primary" href={% url 'articles:detail' b.id %}>Перейти</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    <hr>
    <div style="text-align: center;">
        <div class="col d-flex justify-content-center ">
            <div class="card w-50 bg-{{ color }} text-dark">
                <div class="card-body">
                    <h5 class="card-title">Облако тегов</h5>
                {% if color == 'secondary' %}
                    {% for tag in tags %}
                        <em><a href="{% url 'articles:bytags' tag.id %}" class="card-text"><span class="btn btn-primary">{{ tag.name }}</span></a></em>
                    {% endfor %}
                {% else %}
                    {% for tag in tags %}
                        <em><a href="{% url 'articles:bytags' tag.id %}" class="card-text"><span class="btn btn-secondary">{{ tag.name }}</span></a></em>
                    {% endfor %}
                {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

</body>
</html>